---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cpt
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"